variable "aws_access_key" { }
variable "aws_secret_key" { }
variable "aws_session_token" { }
variable "aws_region" { }
variable "identifier" { }
variable "key_pair" { }
variable "owner" { }
variable "hc_region" { }
variable "purpose" { }
variable "ttl" { }
